### ISSUE TITLE
If temp folder is deleted the /mail folder is not recreated

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#1]
This leaves no place for the mail to place it's files. A check should be in place to see if the folder exists if not recreate it.

**Comment by Steveorevo** [comment]
Mail is apart of core. Moving this issue to DS3 as mail, web, and database is apart of DesktopServer. Deleting of the temp folder can disrupt or damage the DesktopServer installation/operation (its actually the PHP runtime that needs the temp/mail folder). Mailviewer is just for mail viewing and is not apart of core functionality.
