### ISSUE TITLE
Add domain name/site that created email to view pane

### ISSUE THREAD

**Issue by davejesch** [ServerPress/mailbox-viewer#10]
#### STEPS TO REPRODUCE: 
1. View emails for sites (http://localhost/ds-plugins/mailbox-viewer/page.php)

#### RESULT: 
Note that all emails from all sites under DS are displayed- but you don't know which site an email is from.

#### EXPECTED RESULT: 
Need to add a "Domain" column to indicate the site that created the email.

Additionally, when deleting or renaming a site- do we need to delete the emails? Do we need to rename the "domain" value stored with the email when a site is renamed?

**Comment by davejesch** [comment]
Added 'Domain' column to list of emails add added the domain name to the SMTP headers via PhpMailer

**Comment by GreggFranklin** [comment]
Tested in DS 3.9! Works Great.

**Comment by GreggFranklin** [comment]
Great addition. Closing
