### ISSUE TITLE
Emails not showing

### ISSUE THREAD

**Issue by Apina** [ServerPress/mailbox-viewer#13]
#### STEPS TO REPRODUCE: 
1. Was running older version of Mailbox Viewer (MV) (maybe original, certainly 1.0.4 or lower)
2.  Updated to latest version, emails stopped showing
3. Upgraded from DS 3.8.2 to 3.8.3 with no change
4. Downgraded MV to 1.0.4 and emails showed again. (I tried a few versions in between with no luck)

Screenshot http://take.ms/jvtVp

#### RESULT: 
No email showing, but I know some exist. Tried sending new emails from dev project and Check Emails plugin. Nothing showed.

#### EXPECTED RESULT: 
Being able to see emails.

Browser:  Chrome
Browser Version:  Version 59.0.3071.115 (Official Build) (64-bit) (also updated and tested with latest version)

Also tried Firefox 54.0.1 (32-bit)

Operating System: Windows 7 64bit

**Comment by davejesch** [comment]
Related to #6.

We've changed directory locations of the email files for the 3.9 release. I'll make some changes so that it's backward compatible when the plugin is running under DS 3.8.x. I should have a fix later today.

**Comment by GreggFranklin** [comment]
This issue is resolved
