### ISSUE TITLE
No mail is being presented in Mailbox - viewer version 1.0.12

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#14]
#### STEPS TO REPRODUCE: 
Installation of DS3.9v10
Replaced Mailbox-Viewer with version 1.0.12
Created a new site and went to Mailbox-viewer for New Site email

#### RESULT: 
Nothing found in mailbox-viewer
Checked for temp folder in /applications/DesktopServer/runtime/temp/mail - not created
Checked for temp folder in /applications/DesktopServer/runtime/temp- not created

Attempted manual creation of these two folders and ran the test, no mail

#### EXPECTED RESULT: 
To see mail in the mailbox-viewer screen

Browser:  Chrome
Operating System: Mac OX Sierra

PHP.ini file.
[php.ini.txt](https://github.com/ServerPress/mailbox-viewer/files/1184415/php.ini.txt)

Send Mail (1.1kb) date modified - jul 18
[sendmail.php.zip](https://github.com/ServerPress/mailbox-viewer/files/1184416/sendmail.php.zip)

**Comment by davejesch** [comment]
I think I know what's happening: the creation of the temp directory was removed because it's supposed to be created at install time.  I can temporarily add this back. But in the mean time to verify this: try creating the directory at /Applications/DesktopServer/runtime/temp/mail/. Once that's done, emails should be created and viewable. If not, I'll dig deeper.

**Comment by GreggFranklin** [comment]
We did try that thinking that maybe it was just the creation of the folders. But no success.

**Comment by davejesch** [comment]
Related #13 

Let's try this. Replace the DesktopServer/runtime/platform/all/sendmail.php with this one: 
[sendmail.php.txt](https://github.com/ServerPress/mailbox-viewer/files/1189030/sendmail.php.txt)

Delete the DesktopServer/runtime/temp/mail directory, if previously deleted.

Then try sending an email. This version will create the directory each time an email is sent, but under the permissions of the DS app. So it should work better. If not, let me know and we'll investigate further.

**Comment by GreggFranklin** [comment]
This issue is resolved
