### ISSUE TITLE
Present an alert if the client has installed the Mailbox Viewer in WordPress instead of in the ds-plugins folder

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#17]
STEPS TO REPRODUCE:

    Download plugin and install via WordPress.

RESULT:

An error is produced
EXPECTED RESULT:

An alert instructing them to install it in OS path \ ds-plugins

![screen shot 2018-06-12 at 7 46 16 am](https://user-images.githubusercontent.com/1041421/41297763-bb466522-6e14-11e8-8ee2-c89ea9779786.jpg)

**Comment by davejesch** [comment]
added message

**Comment by GreggFranklin** [comment]
Plugin could not be activated because it triggered a fatal error.

( ! ) Fatal error: Uncaught Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/mailbox-viewer-master/mailbox-viewer.php on line 17
( ! ) Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/mailbox-viewer-master/mailbox-viewer.php on line 17
Call Stack
#	Time	Memory	Function	Location
1	0.0135	648776	{main}( )	.../plugins.php:0
2	0.3427	24574656	plugin_sandbox_scrape( )	.../plugins.php:172
3	0.3429	24581912	include( '/Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/mailbox-viewer-master/mailbox-viewer.php' )	.../plugin.php:1897

**Comment by davejesch** [comment]
fixed callback reference

**Comment by erinmarinas** [comment]
Issue resolved
