### ISSUE TITLE
 Letters with accent "àèìòù" that are not translated well in the message

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#18]
HelpScout ticket: https://secure.helpscout.net/conversation/622226975/202013?folderId=88236

![ecmoahhaiobkfhgp](https://user-images.githubusercontent.com/1041421/43361552-3bfea64e-9286-11e8-903f-a63d0d74baff.png)

**Comment by davejesch** [comment]
Related #8 

I remember fixing something about this in the subject lines before. I think it was some other encoding though, not UTF8.

**Comment by davejesch** [comment]
Code was already present to do UTF-8 binary decoding; added UTF-8 quoted printable decoding capability.

**Comment by GreggFranklin** [comment]
Issue resolved. Confirmed by client
