### ISSUE TITLE
Garbled subject line

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#2]
Ticket: https://secure.helpscout.net/conversation/185953274/113855/?folderId=88236

OS: Macintosh OS X 10.11.X (El Capitan)
DS version: 3.8.1

![garbled-email](https://cloud.githubusercontent.com/assets/1041421/14082663/23e588ee-f4c6-11e5-93fa-82643638f05b.jpg)

**Comment by Steveorevo** [comment]
Do you have the mail file from the temp/mail folder? If so, please attach.

**Comment by GreggFranklin** [comment]
I hope he provided what you were looking for.
[Desktopserver e-mails.zip](https://github.com/ServerPress/mailbox-viewer/files/193754/Desktopserver.e-mails.zip)

**Comment by davejesch** [comment]
Subject lines are not 'garbled', just UTF8 encoded. Need to display decoded value. I think I've got some code somewhere that'll do that from when I was working on an email proxy service.

**Comment by davejesch** [comment]
added decoding of subject

**Comment by GreggFranklin** [comment]
Subject lines look great - closing ticket
