### ISSUE TITLE
Mailbox Viewer - Error: Fatal error: Class 'GString' not found

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#4]
STEPS TO REPRODUCE:

Install current version of Mailbox Viewer and visit http://localhost/ds-plugins/mailbox-viewer/page.php

RESULTS:
![ds-mailbox](https://cloud.githubusercontent.com/assets/1041421/15337321/042672ca-1c30-11e6-81dd-68bca2521902.png)

EXPECTED RESULT:
No error

**Comment by jennifercloake** [comment]
@Steveorevo GString stuff high priority?  If not, let me know, I'll move this to ServerPressBot or something.

**Comment by Steveorevo** [comment]
fixed in 901f2850e8b0eb4640dc37cfc5da0f5aeb1543ad

**Comment by jennifercloake** [comment]
3.8.2 shipped.  Closing Issue.  Will open another if issue resurfaces.
