### ISSUE TITLE
Email Timestamp is 3 hours different

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#6]
#### STEPS TO REPRODUCE:
1. Create a site
2. Go to the page to login and click the forgot password
3. Send Username or email to have WordPress create an email
#### RESULT:

In the Mail Viewer the timestamp shows 3 hours different then local time. The test was sent at 7:04am
![screen shot 2016-09-13 at 7 05 02 am](https://cloud.githubusercontent.com/assets/1041421/18476952/ccaafb46-7980-11e6-9eaf-7def95dca742.png)

*I thought it had to do with the time set in Settings in WordPress, however I changed that and still received then same 3 hour difference.
#### EXPECTED RESULT:

To show the correct time based on my location.

**Comment by Steveorevo** [comment]
Hmm, wondering if its all on GMT or if it's a local PHP setting. Can you supply phpinfo() output?

**Comment by GreggFranklin** [comment]
![phpinfo](https://cloud.githubusercontent.com/assets/1041421/18499965/644b2224-79f8-11e6-84ee-82e3197c4a19.png)

**Comment by davejesch** [comment]
@GreggFranklin Changing the timezone settings in WP won't change existing emails. Can you try again but change the timezone in WP, then create a new email and see if the times are matched up? We might need to convert times to GMT and store that in order to get these to show correctly. And do we have a setting somewhere for DS's timezone? That could be different from the site(s) running under DS.

**Comment by davejesch** [comment]
Now grabbing the Date: SMTP header value and using that for date of email. This fix works for existing emails since the Date: header is part of the content.

**Comment by GreggFranklin** [comment]
Here is the results of a test sent at 3:37PM

![screen shot 2017-07-26 at 3 41 29 pm](https://user-images.githubusercontent.com/1041421/28646902-fd21ca16-7218-11e7-9894-d381d1117a82.jpg)

**Comment by davejesch** [comment]
Just checking but...what is the timezone setting for that WP install?

**Comment by GreggFranklin** [comment]
Timezone UTC+0

**Comment by davejesch** [comment]
Set the timezone to Los Angeles and generate another email. There should be no difference.

**Comment by GreggFranklin** [comment]
After setting the Timezone to Los Angeles and setting up a new user at 6:32am 
![screen shot 2017-07-27 at 6 32 30 am](https://user-images.githubusercontent.com/1041421/28672820-a736c976-7295-11e7-86f6-81b7aa30db8e.jpg)

Here is the result:
![screen shot 2017-07-27 at 6 32 53 am](https://user-images.githubusercontent.com/1041421/28672833-b3da637c-7295-11e7-8951-76e4d3bb935e.jpg)

**Comment by davejesch** [comment]
Looks like PHPMailer is not taking the timezone setting from WP. I'll check that out.

**Comment by GreggFranklin** [comment]
Tested on 3.9 works perfectly. Odd on my 3.8.3, MailViewer is not working. No new messages coming in.

**Comment by davejesch** [comment]
You mean using this version of the Mailbox Viewer with DS 3.8.3? There may be a PHP compatibility problem. Take a look at the PHP error log file in DS 3.8.3 and see if there's anything in there.

If this needs to be compatible with both DS versions, we can do that - just need to know where to make the adjustments. The log file contents should help with that.

**Comment by GreggFranklin** [comment]
I do not see anything regarding the MailboxViewer in the error_log.

**Comment by davejesch** [comment]
Made backward compatible with DS 3.8.x by checking for and using the DS 3.8.x directory for email files. Should now with with 3.8.x and 3.9.

**Comment by GreggFranklin** [comment]
This issue is resolved
