### ISSUE TITLE
1.0.9: Version notification values sync’d - Comment

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/mailbox-viewer#9]
This should really be removed or revisited to parse the standard header.

**Comment by GreggFranklin** [comment]
Steve, Dan Griffith added this. If you feel it does not fit with how all our plugins work, please feel free to remove it.

**Comment by davejesch** [comment]
The code that performs version checking to provide the notice to update the plugin needs to be removed.

**Comment by davejesch** [comment]
removed version check code

**Comment by GreggFranklin** [comment]
Thanks Dave for removing this code. Closing
